### ISSUE TITLE
Header for ABC Swap

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/ABCswap#19]
1. About ABC = https://www.commonsstack.org/augmented-bonding-curve

2. Since this is the Swap page, the "other" link should be ABC Luanchpad

ABC Launchpad = https://launch.abcswap.xyz 

3. The leftmost "ABC Swap" looks so weak and wimpy. We should remove it for now. Until we have something better.

<img width="1063" alt="Screenshot 2023-10-18 at 9 57 59 AM" src="https://github.com/commons-stack/ABCswap/assets/703624/5aa8e21d-266f-42e6-ae49-ab8e4c156e1d">

**Comment by tamarandom** [comment]
Are the links added too? I can't tell from the screenshot.

**Comment by jorvixsky** [comment]
Yes, they are. As you can see in the comment just added at issue #26, there is nothing that hints that they're links and maybe we can agree on how links should appear. Let's talk it in the meeting we have in 10'

**Comment by tamarandom** [comment]
Small note: ABC Launch. (can we remove pad)

**Comment by jorvixsky** [comment]
Header OK as agreed on meeting, and already changed all "ABC Launchpad" to "ABC Launch".
