### ISSUE TITLE
Swap main page - copy change

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/ABCswap#20]
This didn't make it into the final design in time but change "Where you can find and swap you favorite DAO's ABC tokens." to "Find and swap ABC tokens."

<img width="376" alt="Screenshot 2023-10-18 at 10 04 47 AM" src="https://github.com/commons-stack/ABCswap/assets/703624/efce41c5-7643-4ebe-b39c-2d513ef0a889">

**Comment by jorvixsky** [comment]
Done.

Looks like that: 
![image](https://github.com/commons-stack/ABCswap/assets/16840805/7f9e5bfd-e1d8-4497-8461-1cda10dbb9a9)


Will be added for PR with other issues @sembrestels @pinglu-pingu.

@tamarandom if it is OK to you, you can now close the issue.
