### ISSUE TITLE
Swap main page - spacing issue 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/ABCswap#21]
See the Fleek: 
<img width="640" alt="Screenshot 2023-10-18 at 10 06 16 AM" src="https://github.com/commons-stack/ABCswap/assets/703624/2c4d4f39-194e-40b2-94e0-783ad2239ebb">

Versus the Figma: 
<img width="315" alt="Screenshot 2023-10-18 at 10 07 10 AM" src="https://github.com/commons-stack/ABCswap/assets/703624/60025ff0-705b-4851-8485-2059e26659ee">

**Comment by jorvixsky** [comment]
Is it better now? 

![image](https://github.com/commons-stack/ABCswap/assets/16840805/3aa56a66-6a5b-4a75-a74c-6d343cc7900d)

I can make everything look closer, but I think having some space between the items looks good.

**Comment by tamarandom** [comment]
So the questions and answer should be closer together. 
Question: what do you want to swap
Answer: entered token

The Next, is just part of the flow. So it should be the one with more spacing from the rest.

**Comment by jorvixsky** [comment]
Changed and now OK as agreed on meeting.

![image](https://github.com/commons-stack/ABCswap/assets/16840805/980e40fe-0356-49cf-bcb4-6b579793ff7d)

**Comment by tamarandom** [comment]
On F

<img width="732" alt="Screenshot 2023-10-18 at 9 42 04 PM" src="https://github.com/commons-stack/ABCswap/assets/703624/aa025253-2053-41fc-b1da-379b172e6cc1">

**Comment by jorvixsky** [comment]
Solved! sorry, it got lost while merging to push to Fleek. Will appear as soon as we push a new version to Fleek (@sembrestels it is in my branch, wlil ask for PR with several changes later)

**Comment by jorvixsky** [comment]
@tamarandom I forgot to mention. The red indicates that there is an error with the DAO name. In this case is appearing (unless you tell me the opposite) because you wrote something and removed it, which keeps it red.

**Comment by tamarandom** [comment]
I see it's fixed already. @jorvixsky I am closing this. 

I like the solution to indicate "not found" by the icon alone. And not make the outline red too. That looks elegant.
<img width="639" alt="Screenshot 2023-10-19 at 3 37 04 PM" src="https://github.com/commons-stack/ABCswap/assets/703624/a43ea429-739b-4d0b-8c8c-9cc9e89f16cd">
