### ISSUE TITLE
Main swap page : next box should not be clickable yet

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/ABCswap#22]
The "next" button should not be clickable until there is matched text in the box. 

<img width="677" alt="Screenshot 2023-10-18 at 12 27 16 PM" src="https://github.com/commons-stack/ABCswap/assets/703624/c89454e0-d0c1-4c96-aa7b-9de2b5b17556">

**Comment by jorvixsky** [comment]
![image](https://github.com/commons-stack/ABCswap/assets/16840805/94b6e862-fb54-4200-a7ea-398e52eefb14)

![image](https://github.com/commons-stack/ABCswap/assets/16840805/bf41a7ec-39b7-4be8-9d76-942161085945)

Now it is behaving correctly (you should be able to see that in Fleek already, if you can confirm and it is OK, you can close the issue)
