### ISSUE TITLE
Main Swap page : Matching DAO name or smart contract is not working

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/ABCswap#23]
<img width="659" alt="Screenshot 2023-10-18 at 12 29 15 PM" src="https://github.com/commons-stack/ABCswap/assets/703624/056ca2b1-e762-4f4a-aba6-4aa16bca0068">

**Comment by jorvixsky** [comment]
This is now live on Fleek, if you could please confirm that it works as expected and if so close the issue.

**Comment by tamarandom** [comment]
Nice! Closing.
