### ISSUE TITLE
Main Swap page: Fix the copy 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/ABCswap#24]
Fleek: 
<img width="448" alt="Screenshot 2023-10-18 at 12 30 12 PM" src="https://github.com/commons-stack/ABCswap/assets/703624/1943a35d-0d59-4805-9335-44bc0cc6d191">

Figma: 
<img width="894" alt="Screenshot 2023-10-18 at 12 31 04 PM" src="https://github.com/commons-stack/ABCswap/assets/703624/b568fd7d-c746-46d8-ac60-7fad99929d49">

**Comment by jorvixsky** [comment]
![image](https://github.com/commons-stack/ABCswap/assets/16840805/cf37a7e8-a92a-42c8-b8aa-8a7e6cd187cb)

Fixed! 

Will be added to the project in a PR with other changes, I close this issue.
