### ISSUE TITLE
Swap page : Only show 4 digits after the decimal point 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/ABCswap#25]
Only show 4 digits after the decimal point for send/receive, balance and the exchange rate

<img width="909" alt="Screenshot 2023-10-18 at 12 32 40 PM" src="https://github.com/commons-stack/ABCswap/assets/703624/75d3ebad-6a96-4937-a8f8-d0c9f007a80f">

**Comment by pinglu-pingu** [comment]
Fixed. Attaching video:

[Screencast from 19-10-23 18:37:27.webm](https://github.com/commons-stack/ABCswap/assets/141140367/e791d692-fc9c-4b1f-a4e3-82d761bb3e92)

**Comment by tamarandom** [comment]
Pretty!
