### ISSUE TITLE
Footer 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/ABCswap#27]
The finally agreed upon footer is a little hidden in the Figma. But you can find it here: 
https://www.figma.com/file/1pUuoFBtGHEuXSwyMgH7eh/Commons-Stack-ABC-Swap-and-Launchpad?type=design&node-id=308-2046&mode=design

@jorvixsky I tagged you in the Figma so hopefully you can find it by looking for my comment.

<img width="698" alt="Screenshot 2023-10-18 at 12 58 28 PM" src="https://github.com/commons-stack/ABCswap/assets/703624/f0e863cc-2335-43b0-8d3b-14c725d59251">

**Comment by tamarandom** [comment]
Also: for the "all rights reserved", use "2023 ABC Labs"

**Comment by jorvixsky** [comment]
![image](https://github.com/commons-stack/ABCswap/assets/16840805/fa6047f4-a2b2-42e6-8c5a-c40528ed92d8)

Done! Already uploaded at Fleek. Closing the issue.
