### ISSUE TITLE
Swap And Launch: Terms and Conditions 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/ABCswap#28]
This is where they are being drafted and reviewed by the lawyer. 
Note that they are not reviewed yet. 
ETA today.

https://docs.google.com/document/d/1a3NzTYLypiwHriqCQ3vP1XoJptOWjRyNeVG-u-WH9_E/edit

**Comment by tamarandom** [comment]
Jose's edits are in here but we will do final review together tomorrow morning and then consider this closed. 
https://docs.google.com/document/d/1rDBHDQFh6FAqr8EOqzVpDjJr9eLNOtXnys2n2JlQybQ/edit#heading=h.37zvjzgf0upd

**Comment by jorvixsky** [comment]
Closed as duplicated, continues in #42
