### ISSUE TITLE
Icons and cards for link shares 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/ABCswap#31]
1. For Favicon, use CS one.

2. For publish link on Twitter, discord, TG, etc "publish card" 

(For example, see below:)
<img width="427" alt="Screenshot 2023-10-18 at 2 11 09 PM" src="https://github.com/commons-stack/ABCswap/assets/703624/0f3c55a2-a8e8-4cc6-b266-82e9e6fc3e70">

**Comment by tamarandom** [comment]
(Not sure if the dimensions for the images work, lmk)

FOR SWAP:
<URL>
abcswap.xyz
**(bold) ABC Swap | Find and swap ABC tokens**

![abcswap](https://github.com/commons-stack/ABCswap/assets/703624/b144d2fb-e5ba-48ee-85a8-0b4ddb967e19)


FOR LAUNCH:
<URL>
launch.abcswap.xyz
**(bold) ABC Launch | The only place to launch an Augmented Bonding Curve.** 
Launch an ABC with a new DAO or attach one to your existing DAO.

![abclaunch](https://github.com/commons-stack/ABCswap/assets/703624/04e74533-3b1b-4d6f-9979-73c0c22d0ec5)


--- FYI used the below as a model --- 
<img width="324" alt="Screenshot 2023-10-18 at 4 56 04 PM" src="https://github.com/commons-stack/ABCswap/assets/703624/e9c7bd46-2964-4cb9-b6ea-e52b9396633a">

**Comment by jorvixsky** [comment]
Shared by @sembrestels on our internal chat:

![image](https://github.com/commons-stack/ABCswap/assets/16840805/6f225a65-4062-43cb-87b9-de66722c8ef0)

![image](https://github.com/commons-stack/ABCswap/assets/16840805/ae1eda50-3c66-4fa6-9c23-507525b5e157)

Ok'd by @tamarandom, closing the issue.
