### ISSUE TITLE
Website usability - responsive

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/ABCswap#33]
Although we did de-prioritize being able to use the site on mobile devices, the desktop version's "responsiveness" looks very bad. Here are just a couple of examples. What can be done?

This one is just broken:
<img width="717" alt="Screenshot 2023-10-18 at 9 37 48 PM" src="https://github.com/commons-stack/ABCswap/assets/703624/7162ba25-a1b0-4d84-bd43-08b48f48d5e7">

This one loses the "next" button:
<img width="990" alt="Screenshot 2023-10-18 at 9 37 54 PM" src="https://github.com/commons-stack/ABCswap/assets/703624/cb00a04d-1f9f-4394-8267-8b5edf4ef1ec">

**Comment by jorvixsky** [comment]
@tamarandom for the Swap:

![image](https://github.com/commons-stack/ABCswap/assets/16840805/7bbb6425-0d6a-4f6b-acc2-03ab5e1ccb3a)

In a wider screen would look like that: 

![image](https://github.com/commons-stack/ABCswap/assets/16840805/2b7ed3cf-16f1-4330-9bd5-bb1e7dea6b81)

As you see I had to change the position of the text in relation to corresponding icons, don't know if it is OK in terms of design but it is a way to enhance the responsiveness on desktop (also will improve it in mobile, as a side effect)

I can make this kind of adjustments for the rest of the apps. 

Regarding the button that disappears, could you explain me it a bit more? Tinkered with screen sizes and I don't see that happening.

**Comment by tamarandom** [comment]
Better. Let's go with this. TY @jorvixsky. Shall I close this issue?

**Comment by jorvixsky** [comment]
@tamarandom with the testing you have been doing, did you see anything that would affect this issue? If not probably we can close it now

**Comment by tamarandom** [comment]
Sure, let's close. It is an issue but not for the MVP.
