### ISSUE TITLE
Swap page / Functionality - should say if a matched DAO does not have an ABC

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/ABCswap#34]
This should throw an error that says that tamara DAO does not have an ABC. (Tamara is a DAO but it does not have an ABC). Instead it allows me to "next" to the swap page.

<img width="496" alt="Screenshot 2023-10-18 at 9 45 19 PM" src="https://github.com/commons-stack/ABCswap/assets/703624/69703f7a-189c-4fc1-84bb-044eff816512">

**Comment by jorvixsky** [comment]
@sembrestels tagging you to this issue.

**Comment by jorvixsky** [comment]
This is live now on Fleek

**Comment by tamarandom** [comment]
Closing. Opened issue about using diff error messages but consider this no longer blocking.
