### ISSUE TITLE
Launch + Swap main pages: copy 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/ABCswap#35]
"Welcome to ABC Swap" (let's take out the "the")
<img width="900" alt="Screenshot 2023-10-18 at 9 48 59 PM" src="https://github.com/commons-stack/ABCswap/assets/703624/7abd6ef4-5ada-40c6-a4f0-bc80d43d5d9d">

And make this one match with: "Welcome to ABC Launch"
<img width="648" alt="Screenshot 2023-10-18 at 9 48 52 PM" src="https://github.com/commons-stack/ABCswap/assets/703624/49166a49-2dcf-43b2-9ae4-2eaff35b7583">

**Comment by jorvixsky** [comment]
Changed, now looks as below:

![image](https://github.com/commons-stack/ABCswap/assets/16840805/cfa8c148-f2eb-4081-8a46-2a6e01207519)

![image](https://github.com/commons-stack/ABCswap/assets/16840805/db6db554-0fe1-4a84-8a4d-13ebcc4f623c)

**Comment by jorvixsky** [comment]
![image](https://github.com/commons-stack/ABCswap/assets/16840805/ffa8823f-d735-4650-9c9f-180f6d0f3a2b)

Removed the exclamation point, you can close the issue if it is OK

**Comment by tamarandom** [comment]
Perfect.
