### ISSUE TITLE
Launch, but also in general : So. Much. Space. 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/ABCswap#36]
The designs have a lot of space. Too much to be honest. But actually using the site, it's truly terrible UX to keep having to make the screen size larger and larger. Especially considering how few parameters there actually are. What can we do to tighten this up? Eventually we may need tighter designs but what can be done quickly?

<img width="1135" alt="Screenshot 2023-10-18 at 9 54 04 PM" src="https://github.com/commons-stack/ABCswap/assets/703624/d4299d81-c13f-4b52-bffe-2aa320598c97">

**Comment by jorvixsky** [comment]
An option would be to cut the margins in half or 1/3rd of what there is currently, and for v2 we can rethink the design.

Do you want me to go with that? An example for the voting would be this:

![image](https://github.com/commons-stack/ABCswap/assets/16840805/25b77e4c-eec1-4bb1-a013-026da33dca4e)

**Comment by tamarandom** [comment]
yes! That looks a lot better already!

**Comment by jorvixsky** [comment]
![image](https://github.com/commons-stack/ABCswap/assets/16840805/dff49850-1edf-4333-99b5-27995ebde6bb)

![image](https://github.com/commons-stack/ABCswap/assets/16840805/59346cf8-b940-451a-8ba2-2c442f1b7df5)

![image](https://github.com/commons-stack/ABCswap/assets/16840805/ab2a9077-116b-4e4f-9874-1da86e774092)

@tamarandom could you please check it this looks better?
