### ISSUE TITLE
Launch Token page: Need better copy here.

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/ABCswap#38]
<img width="554" alt="Screenshot 2023-10-18 at 10 00 21 PM" src="https://github.com/commons-stack/ABCswap/assets/703624/69f42e3a-41ed-4a29-ab14-7f15806c98fc">

**Comment by tamarandom** [comment]
Here is the text @jorvixsky ! It was already in the Figma but only in the design+copy page, not the final designs one. That's how you missed it.

These settings will determine the name and symbol of the token that will be created for your organization. Add members to define the initial distribution of this token.

<img width="698" alt="Screenshot 2023-10-19 at 3 30 01 PM" src="https://github.com/commons-stack/ABCswap/assets/703624/9072e50d-f518-4e89-ab2f-f20690bcdd57">

**Comment by jorvixsky** [comment]
Changed, looks like this now: 

![image](https://github.com/commons-stack/ABCswap/assets/16840805/c9178729-4323-407f-85e5-5e769b36c248)

You can close the issue if it is OK

**Comment by tamarandom** [comment]
woot!
