### ISSUE TITLE
Launch final page - error

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/ABCswap#40]
I got this error but no idea why. 

<img width="655" alt="Screenshot 2023-10-18 at 10 04 08 PM" src="https://github.com/commons-stack/ABCswap/assets/703624/56a2e4ec-f3d6-4296-8ff5-45bba28cfc99">

**Comment by sembrestels** [comment]
Sometimes is metamask that failed to calculate the gas, and it works again when you retry. Next time it happens, please open the [browser console](https://balsamiq.com/support/faqs/browserconsole/) (F12) and check which error it does give.

Otherwise, if it works next time, we can close this issue.

**Comment by jorvixsky** [comment]
As explained by @sembrestels, this can happen due to the DAO name already existing (which is currently verified) and the user not having the funds set as initial reserve, which is now handled by issue #54 and will be tackled there, so I am closing this one to avoid duplicity.

**Comment by tamarandom** [comment]
Cool.
