### ISSUE TITLE
Launch : final page new copy

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/ABCswap#41]
We don't have a design for this one, right? 

The first one should be the same as swap page (see screenshot below)
Approve Spending / Waiting for signature / Signed

The second one...
Launch ABC and DAO / Waiting for signature / Signed 
<img width="732" alt="Screenshot 2023-10-18 at 10 05 10 PM" src="https://github.com/commons-stack/ABCswap/assets/703624/cbbd5ca0-a0f5-43ac-935c-bc9c2aa33d0b">

See swap example here:
<img width="472" alt="Screenshot 2023-10-18 at 10 05 58 PM" src="https://github.com/commons-stack/ABCswap/assets/703624/64a6216c-cf31-4cf5-ac0a-40376eac2c67">

**Comment by jorvixsky** [comment]
@tamarandom they are the same as they are using the exact same component to standardize, so they should look the same.

I see that the difference with the Figma is that the title is in CS green, and the background is this cream-like color. I am changing that.

Do you see anything else that should be changed?

**Comment by jorvixsky** [comment]
This is how it looks now with my last changes, for reference:

![image](https://github.com/commons-stack/ABCswap/assets/16840805/9a865e31-628e-4b45-a5c3-465e1ea4abac)

**Comment by tamarandom** [comment]
It still says "raise approval"? And "Make buy order". 

The text should be:

**Approve Spending** / Waiting for signature / Signed

The second one...
**Launch ABC and DAO** / Waiting for signature / Signed

**Comment by tamarandom** [comment]
I see that might not have been clear in my first message!

**Comment by jorvixsky** [comment]
Oh now I see it!! Changed. 

Swap:

![image](https://github.com/commons-stack/ABCswap/assets/16840805/dfc1b179-f9f6-487e-b988-1831290e4f25)

Launch:

![image](https://github.com/commons-stack/ABCswap/assets/16840805/cd23679d-f985-40ea-8c96-746be2c0bbb0)

If you could please confirm that now it is final and if so close the issue.

**Comment by tamarandom** [comment]
The swap flow has the wording correct. Just need to use the same (i.e., waiting for signature and signed):
<img width="1417" alt="Screenshot 2023-10-19 at 3 40 44 PM" src="https://github.com/commons-stack/ABCswap/assets/703624/71818870-23f5-4b7c-af53-61c69c708b18">

**Comment by tamarandom** [comment]
I still see the old text, btw. I assume bc not yet merged. @jorvixsky 

<img width="1052" alt="Screenshot 2023-10-19 at 3 49 11 PM" src="https://github.com/commons-stack/ABCswap/assets/703624/c10a77f4-2239-4072-a4b0-4a8d9b940e56">

**Comment by jorvixsky** [comment]
Other copy changed (Waiting for signature and signed), and yes, not yet merged.
