### ISSUE TITLE
Terms of Service

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/ABCswap#42]
This is for BOTH the ABC Swap and ABC Launch services. 

https://docs.google.com/document/d/1rDBHDQFh6FAqr8EOqzVpDjJr9eLNOtXnys2n2JlQybQ/edit

**Comment by jorvixsky** [comment]
Working on it (creating modal). Question, isn't this issue duplicated on this another #28 ?

**Comment by tamarandom** [comment]
Yes! It is.

**Comment by jorvixsky** [comment]
Already uploaded on Fleek, if you can check it out. We will do an improvement later on how the text is grabbed to make maintenance easier (in case it is necessary to make changes in the future)

**Comment by iviangita** [comment]
Some edits @jorvixsky:

1) Please move this text before ABC Swap (it's part of ABC Launch)

<img width="726" alt="image" src="https://github.com/commons-stack/ABCswap/assets/74632674/b61018d9-4a5f-47b9-ab8c-a2f889efa64d">

2) This intro text is missing under ABC Swap - please add

<img width="561" alt="image" src="https://github.com/commons-stack/ABCswap/assets/74632674/f26b295c-5650-44d6-a1d6-ab1a41f39897">

3) Change to uppercase A

<img width="678" alt="image" src="https://github.com/commons-stack/ABCswap/assets/74632674/e88a1981-5d46-4486-9a56-80220e7504d2">

4) Should be ABC Launch - please fix

<img width="699" alt="image" src="https://github.com/commons-stack/ABCswap/assets/74632674/8571b910-99a2-4860-aee0-499c5ec8bfae">


5) Please remove the extra spaces before the punctuations and update the Privacy Policy link when it's ready

<img width="725" alt="image" src="https://github.com/commons-stack/ABCswap/assets/74632674/39405f00-5b15-4521-b3a1-f21fa142ef95">

**Comment by jorvixsky** [comment]
@iviangita fixed these changes. Need a IPFS link with the PDFs to be able to link the docs when at the modal.

It has been merged in a PR, pending deployment (I'll let you know when it's deployed)

**Comment by jorvixsky** [comment]
Live now for review @iviangita

**Comment by tamarandom** [comment]
@jorvixsky 

The privacy policy refers to the TOS link
The TOS link refers to the Privacy policy link

This will be an issue when uploading the pdf to IPFS, right? 

Should'd we have something like: 
abcswap.xyz/terms
abxswap.xyz/privacy

**Comment by jorvixsky** [comment]
My idea was to put the IPFS link in those references for that specific reason (as modal cannot be linked) 

Anyway let me see If I can quickly do those /terms & /privacy as I think we have time for that.

**Comment by tamarandom** [comment]
Cool.

**Comment by tamarandom** [comment]
Perfect.

**Comment by jorvixsky** [comment]
This is now live on Fleek, if you go to the modals with the terms & policy you will see that the links are there.

You can access directly here:

https://abcswap.on.fleek.co/#/privacy
https://abcswap.on.fleek.co/#/terms

Note that the links in the respective documents do not work as they are pointing to the final domain (abcswap.zyx), they will work as soon as we do the final deployment.

**Comment by tamarandom** [comment]
Looks good to me. Closing.
