### ISSUE TITLE
ABC Launch Error when I mistyped a letter instead of a number in the Vote Duration

### ISSUE THREAD

**Issue by iviangita** [commons-stack/ABCswap#45]
I was trying to put a value in the Hours box under Vote Duration but accidentally hit on a letter instead of a number on my keyboard then got this error message. I also get the same error message when I'm trying to go back to the previous page. It only goes away when I refresh the page. Is there a way to not show this error message? Otherwise, I think we need to create a better error message if it has to stay.

<img width="952" alt="image" src="https://github.com/commons-stack/ABCswap/assets/74632674/4ee884bf-9445-48e2-8b9a-aea7e53b0d4c">

**Comment by jorvixsky** [comment]
This should not happen at all, we've detected it happened on a couple of inputs. @sembrestels could you take a look at this one?
