### ISSUE TITLE
Launch page: two check boxes for the final check

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/ABCswap#47]
Looking at this live, it really should be 2 check boxes

[ ]  I confirm that the above information is correct.
[ ] I have read and agree to the Terms of Service and Privacy Policy 

<img width="839" alt="Screenshot 2023-10-19 at 3 45 56 PM" src="https://github.com/commons-stack/ABCswap/assets/703624/2f876931-3357-4d28-beaf-25fbfea792e4">

**Comment by jorvixsky** [comment]
![image](https://github.com/commons-stack/ABCswap/assets/16840805/7f9e7f81-ba67-4cc7-82a4-fac886a5595a)

Already added to PR and merged, pending to deploy. Looks like this.

**Comment by jorvixsky** [comment]
Live for review.

**Comment by tamarandom** [comment]
Small point but can we tone down the blue color. Or go back to the non-bold text for the sentences and underline the ToS and PP. More subtle. Second option is probably better.

**Comment by jorvixsky** [comment]
![image](https://github.com/commons-stack/ABCswap/assets/16840805/f752e9d4-6d8f-490a-ad56-9f7a86dba196)

Would look like this, what do you think?

**Comment by tamarandom** [comment]
Perfect, @jorvixsky!

**Comment by tamarandom** [comment]
Yep, saw. looks good. Closing.
