### ISSUE TITLE
Launch DAO+ABC:  What does "unapproved" mean in this Metamask Activity?

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/ABCswap#48]
<img width="349" alt="Screenshot 2023-10-19 at 3 49 55 PM" src="https://github.com/commons-stack/ABCswap/assets/703624/38b1c2a8-08ed-461b-a69a-3e30a95baf18">

**Comment by tamarandom** [comment]
Before I signed the second one, I see MM activity looks like this:

<img width="364" alt="Screenshot 2023-10-19 at 3 51 58 PM" src="https://github.com/commons-stack/ABCswap/assets/703624/5c3712ac-7925-4cf3-bff0-eff4cbc1a75a">

**Comment by jorvixsky** [comment]
Looking at your 2nd message, probably it is because Metamask kept open before prompting the transaction signature but already queued it. Did it happen again?

**Comment by tamarandom** [comment]
Yes.

I assume the second request is sent before the first has a chance to actually execute. Hence the message.

<img width="358" alt="Screenshot 2023-10-20 at 8 24 04 AM" src="https://github.com/commons-stack/ABCswap/assets/703624/05d0456e-2b6d-4c62-85f0-5c25454322cc">

**Comment by tamarandom** [comment]
Sorry the above is a bit different that the original image but maybe actually same problem seen from a different angle.

**Comment by tamarandom** [comment]
It does actually clear, of course, once the first tx is executed.

**Comment by jorvixsky** [comment]
I think this is normal then, may we close this one?

**Comment by tamarandom** [comment]
Is there any way to fix it? Introduce a delay between sending the 2 transactions?

If we want to fix after MVP launch, change the tag to enhancements. OK with that.

**Comment by jorvixsky** [comment]
Thing is I checked the code and it waits for the 1st transaction to succeed and then awaits for its confirmation before proceeding to launch the 2nd one. I also have not been able to reproduce the issue on Chrome. Maybe we can go over it when we meet again and try to reproduce it and see if we get more insights about why it is happening to you, because honestly right now I don't see anything on our side that could cause this issue.

**Comment by tamarandom** [comment]
I have not seen this again. Closing.
