### ISSUE TITLE
Launch DAO+ABC: How long should it take? 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/ABCswap#49]
If it is normal that this takes a long time, we will want to notify the user. It's been maybe a minute so far. Too long to not inform the user to be patient. 

<img width="1156" alt="Screenshot 2023-10-19 at 3 52 13 PM" src="https://github.com/commons-stack/ABCswap/assets/703624/2f38bfd3-761c-4990-8635-d81dd3adaefd">

**Comment by jorvixsky** [comment]
Really weird, just tried and took just a few seconds to launch the DAO...

**Comment by tamarandom** [comment]
Still not working for me. As you saw. Needs to direct user to Swap and Governance pages. 
<img width="532" alt="Screenshot 2023-10-19 at 4 49 20 PM" src="https://github.com/commons-stack/ABCswap/assets/703624/e94ef4ae-1cb8-4253-92bc-7353ee31a1bf">

**Comment by pinglu-pingu** [comment]
Added logic to show the congratulations screen. Styles are missing (@jorvixsky , can you take care of them?)
[Screencast from 20-10-23 00:12:19.webm](https://github.com/commons-stack/ABCswap/assets/141140367/812eb7a5-4ff7-47de-976a-bcd4a158cebf)

**Comment by jorvixsky** [comment]
![image](https://github.com/commons-stack/ABCswap/assets/16840805/d3403c86-3ae9-4768-bd4b-5c975ac7c379)

How it is looking. @tamarandom as agreed for other pages I removed as much blank space as possible. PR'ing now and will be live ASAP.

**Comment by tamarandom** [comment]
Nice. LMK know it's on fleek and I will test.

**Comment by tamarandom** [comment]
Testing...

**Comment by tamarandom** [comment]
Could def use a copy update but that is on me and can be part of the wider, design learnings. Closing this issue!
