### ISSUE TITLE
Swapping token ends.... with no information. 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/ABCswap#51]
After the swap, this pop up just stays there.

<img width="1254" alt="Screenshot 2023-10-19 at 4 22 20 PM" src="https://github.com/commons-stack/ABCswap/assets/703624/2c8ab347-2d12-416a-abeb-33c47bf4e02b">

**Comment by tamarandom** [comment]
Missing close button: 

<img width="380" alt="Screenshot 2023-10-19 at 4 23 29 PM" src="https://github.com/commons-stack/ABCswap/assets/703624/13482395-f988-4cfa-bf26-a5cd7a4fde86">

**Comment by jorvixsky** [comment]
![image](https://github.com/commons-stack/ABCswap/assets/16840805/cf044c09-64f5-48ff-9ed3-8c6b9dc70aaf)

Done. Will be live in the next push to Fleek

**Comment by jorvixsky** [comment]
This is now live. If you can verify it is as expected, and then close the issue if so. Thanks!

**Comment by tamarandom** [comment]
Looks good!
