### ISSUE TITLE
Launch : error for not enough funds in wallet 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/ABCswap#54]
<img width="473" alt="Screenshot 2023-10-19 at 5 02 01 PM" src="https://github.com/commons-stack/ABCswap/assets/703624/3f623ba9-dac6-41f8-8961-ca1fe7fd4d9c">

**Comment by jorvixsky** [comment]
![image](https://github.com/commons-stack/ABCswap/assets/16840805/f19f3fd5-6e02-48c9-8878-06b369a9c3c7)

![image](https://github.com/commons-stack/ABCswap/assets/16840805/e1832d7e-57be-4e1f-8da5-f91849702f2e)

Feature has been added. It is now live on Fleek, if you can validate it. Thanks!

**Comment by tamarandom** [comment]
Looks good. Closing.
