### ISSUE TITLE
Make icons/text smaller. 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/ABCswap#61]
They are so large. Can we try 50% smaller?

<img width="1010" alt="Screenshot 2023-10-20 at 9 54 12 AM" src="https://github.com/commons-stack/ABCswap/assets/703624/f36df82a-ad9d-4ea7-8da1-366d35b57f9e">

**Comment by jorvixsky** [comment]
![image](https://github.com/commons-stack/ABCswap/assets/16840805/4041fb51-92b3-4d27-9afb-a48fd8d16751)

50% looks to small in my opinion.. and adds lots of blank space. We could make items together but we will still have lots of space on the x-axis. I think we need to rethink how to show that information to the user for a next version (design wide, more than adjusting sizes)

**Comment by tamarandom** [comment]
Yeah, you are right. Let's leave it until we can take a more holistic approach instead of piece meal.
