### ISSUE TITLE
Swap: Incorrect entry and exit tribute 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/ABCswap#66]
I am pretty sure they should both be 3% but I am trying to confirm on https://optimism.aragon.blossom.software/#/tamtam/0x6fe1e29d1ca52b4449745fb40662d9c0009ea1e5/

<img width="947" alt="Screenshot 2023-10-20 at 2 10 30 PM" src="https://github.com/commons-stack/ABCswap/assets/703624/aee39827-f08d-4f4e-99e8-baa513ae5a73">

**Comment by jorvixsky** [comment]
Sorry, we pushed to production a version with a hardcoded bonding curve address for testing purposes, which makes it to be always 1 and 2% respectively. Now solved, change will go live in Fleek soon.

**Comment by tamarandom** [comment]
OK.

**Comment by jorvixsky** [comment]
Now live on Fleek

**Comment by jorvixsky** [comment]
Verified that is working at meet
