### ISSUE TITLE
Swap: error messages 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/ABCswap#68]
Error messages for 2 diff use cases:
1. The entered DAO name or contract address was not found. 
2. The entered DAO name does not have an ABC.
3. 
<img width="641" alt="Screenshot 2023-10-20 at 3 30 01 PM" src="https://github.com/commons-stack/ABCswap/assets/703624/7ffaf165-4344-44c7-9a74-b74f7a06558f">

<img width="617" alt="Screenshot 2023-10-20 at 3 30 09 PM" src="https://github.com/commons-stack/ABCswap/assets/703624/f92e0c1b-6ffa-4ff6-92d7-d3ff4d9b1ab0">

**Comment by sembrestels** [comment]
This should be fixed now in https://develop-abcswap.on.fleek.co/

**Comment by tamarandom** [comment]
Working. Closing.
