### ISSUE TITLE
Remove the copy that refers to "contract address" in all input bars 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/ABCswap#74]
As we are moving this feature to a future version, we need to remove the copy which tells the user they can search by contract address. 

1. **For Swap:**
<img width="654" alt="Screenshot 2023-10-27 at 2 38 25 PM" src="https://github.com/commons-stack/ABCswap/assets/703624/7d95f2d7-1c23-498a-b06c-a0e3ac038908">

The text above the input bar asks which token we want to swap. But we are not entering in a token. We are entering in a DAO name. Let's change that too.

Text: "Which DAO's token do you want to swap?"
Input bar text: "Enter DAO name"

2. **For Launch / New DAO:**
<img width="541" alt="Screenshot 2023-10-27 at 2 43 17 PM" src="https://github.com/commons-stack/ABCswap/assets/703624/51f6d281-df59-4a69-9836-8e3f1acc7228">

(the contract address prompt should never be in this flow. We have not yet created it).
Input bar text: "Enter a name for your DAO"

3. **For Launch / New DAO:**
<img width="584" alt="Screenshot 2023-10-27 at 2 47 45 PM" src="https://github.com/commons-stack/ABCswap/assets/703624/fb7976db-ead0-48e2-81bc-7b2ed3e44f9d">

Input bar text: "Enter DAO name"

**Comment by maheshchandra10** [comment]
For the 2nd point (_For Launch / New DAO_), can it have the input bar text as `"Enter DAO name"` instead of `"Enter a name for your DAO"`, same as the rest of the two points have? Because I can see the application is using the **same single component** to add these placeholders for the input box.

**Comment by tamarandom** [comment]
HI @maheshchandra10 👋

For now, yes, it can! Though, eventually, they will have different text because forming a new DAO will never take a contract address as input. See #73

**Comment by maheshchandra10** [comment]
Yeah. I just asked if all the 3 input boxes can have the same placeholder as `"Enter DAO name"`. 

You have asked to add `"Enter a name for your DAO"` as the placeholder for the 2nd input box.
There's just a slight verbiage change between these two.

**Comment by tamarandom** [comment]
Yes, I understood. And yes, it is a great idea for the short term, @maheshchandra10! 
I really appreciate that you jumped in with this suggestion. 🙏
