### ISSUE TITLE
Launch ABC on existing DAO: Should only accept real DAOs

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/ABCswap#75]
Looks like it is accepting any string, whether it matches a real DAO or not.

<img width="590" alt="Screenshot 2023-10-27 at 8 14 02 PM" src="https://github.com/commons-stack/ABCswap/assets/703624/95d1d206-bf7b-4643-960d-4c2db503a784">

**Comment by tamarandom** [comment]
Actually logic is backwards. It won't accept a *real* DAO that I know does not already have an ABC.

<img width="732" alt="Screenshot 2023-10-27 at 8 16 20 PM" src="https://github.com/commons-stack/ABCswap/assets/703624/21d614d7-cd24-4a9d-bee2-283d61485b2b">

**Comment by jorvixsky** [comment]
Sem pushed a fix for this. You can check it now working properly on Fleek, at development branch (https://develop-abclaunch.on.fleek.co)
