### ISSUE TITLE
Swap : Landing page copy 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/ABCswap#79]
On dev: https://develop-abcswap.on.fleek.co/

The text says "Which token do you want to swap" And even though we changed the copy in input box text, it still feels like I am supposed to put in the actual token symbol which, of course, will not work.

New copy: "Enter DAO name to go to their swap page."

<img width="642" alt="Screenshot 2023-10-31 at 2 23 08 PM" src="https://github.com/commons-stack/ABCswap/assets/703624/77c63760-9f6a-4e98-9257-fed2850fba2d">

**Comment by jorvixsky** [comment]
Changed the text. Will go live on Fleek as soon as I PR it with other changes.

**Comment by jorvixsky** [comment]
This is now live on Fleek!

**Comment by tamarandom** [comment]
🌈
