### ISSUE TITLE
Launch: When I change the tribute in one field, it changes both fields 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/ABCswap#82]
on dev: https://develop-abclaunch.on.fleek.co/#/existing-dao/wizard

Does't allow to have different values for entry and exit.

<img width="498" alt="Screenshot 2023-10-31 at 3 01 25 PM" src="https://github.com/commons-stack/ABCswap/assets/703624/ae223491-1930-4dab-9fe9-836209f5035e">

**Comment by tamarandom** [comment]
Though during the confirmation of the details, the exit is set to "0". 

<img width="527" alt="Screenshot 2023-10-31 at 3 06 00 PM" src="https://github.com/commons-stack/ABCswap/assets/703624/b1454b9e-dee3-49be-a5f7-055aeb9fd085">

**Comment by jorvixsky** [comment]
@sembrestels, the state of the exit tribute was using useEntryTributeAtom, changed to the useExitTributeAtom. 

This fixes both issues.

Will be live on Fleek when PR'd.

**Comment by tamarandom** [comment]
Woohoo!!!!!
