### ISSUE TITLE
Launch: typo in text 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/ABCswap#83]
<img width="912" alt="Screenshot 2023-10-31 at 3 05 04 PM" src="https://github.com/commons-stack/ABCswap/assets/703624/daeae44e-e59c-4433-937c-b836959c3983">

**Comment by jorvixsky** [comment]
Fixed the typo. Will go live on Fleek as soon as I PR it with other changes.

**Comment by jorvixsky** [comment]
This is now live on Fleek!

**Comment by tamarandom** [comment]
Wheeeeee!
