### ISSUE TITLE
Add to the list of reserve assets 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/ABCswap#89]
Criteria to add: widely used on Optimism.

Assets to include:
 - wETH
 - rETH (rocket ETH)

<img width="248" alt="Screenshot 2023-11-01 at 4 36 14 PM" src="https://github.com/commons-stack/ABCswap/assets/703624/ce5a1668-7adb-4bcc-9e3d-e51772c1ea1f">

**Comment by tamarandom** [comment]
Note that this will cause the issue of spacing for the price.
<img width="641" alt="Screenshot 2023-11-01 at 4 18 39 PM" src="https://github.com/commons-stack/ABCswap/assets/703624/85e01304-fe66-4c6b-a70e-b58324ee5052">

**Comment by sembrestels** [comment]
Both tokens are added in the latest development version. The issue with the graph axis is difficult to solve, although it doesn't look bad for 1M token supply and 10 ETH in the reserve, which we could consider reasonable numbers for starting a bonding curve.
